require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xpkg"

COMPONENT = "btprogresshud-1.5.xam"

file "xpkg/xpkg.exe" do
	puts "* Downloading xpkg..."
	mkdir "xpkg"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xpkg.zip"
	sh "unzip -o xpkg.zip -d xpkg"
	sh "rm xpkg.zip"
end

task :default => "xpkg/xpkg.exe" do
	line = <<-END
	mono xpkg/xpkg.exe create #{COMPONENT} \
		--name="BTProgressHUD" \
		--summary="Add awesome HUDs to your iOS apps." \
		--publisher="Nic Wise / Big Ted Ltd" \
		--website="http://fastchicken.co.nz/" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/btprogresshud_128x128.png" \
		--icon="icons/btprogresshud_512x512.png" \
		--library="ios":"bin/BTProgressHUD.dll" \
		--sample="iOS Sample. Demonstrates how to use the component on iOS.":"samples/BTProgressHUDSample.sln" 
		END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
