require "rake/clean"

CLEAN.include "*.xam"
CLEAN.include "xamarin-component"

COMPONENT = "btprogresshud-1.8.xam"

file "xamarin-component/xamarin-component.exe" do
	puts "* Downloading xamarin-component..."
	mkdir "xamarin-component"
	sh "curl -L https://components.xamarin.com/submit/xpkg > xamarin-component.zip"
	sh "unzip -o xamarin-component.zip -d xamarin-component"
	sh "rm xamarin-component.zip"
end

task :default => "xamarin-component/xamarin-component.exe" do
	line = <<-END
	mono xamarin-component/xamarin-component.exe create-manually #{COMPONENT} \
		--name="BTProgressHUD" \
		--summary="Add awesome HUDs to your iOS apps." \
		--publisher="Nic Wise / Big Ted Ltd" \
		--website="http://fastchicken.co.nz/" \
		--details="Details.md" \
		--license="License.md" \
		--getting-started="GettingStarted.md" \
		--icon="icons/btprogresshud_128x128.png" \
		--icon="icons/btprogresshud_512x512.png" \
		--library="ios":"bin/BTProgressHUD.dll" \
		--sample="iOS Sample. Demonstrates how to use the component on iOS.":"samples/BTProgressHUDSample.sln" 
    END
	puts "* Creating #{COMPONENT}..."
	puts line.strip.gsub "\t\t", "\\\n    "
	sh line, :verbose => false
	puts "* Created #{COMPONENT}"
end
