name: CI

on: [push]

env:
  xcodeVersion: 16.4
  dotnetVersion: 9.0.304

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Select Xcode ${{ env.xcodeVersion }}
      run: sudo xcode-select -s /Applications/Xcode_${{ env.xcodeVersion }}.app

    - name: Setup .NET ${{ env.dotnetVersion }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnetVersion }}

    - name: Install iOS workload
      run: dotnet workload install maui ios maccatalyst --version $dotnetVersion
      env:
        dotnetVersion: ${{ env.dotnetVersion }}
      
    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Run the Cake script
      run: dotnet run --project build/Build.csproj --artifactsDir ${{ github.workspace }}/artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: NugetPackage
        path: ${{ github.workspace }}/artifacts
