name: CI

on: [push]

env:
  xcodeVersion: 26.0.1
  dotnetVersion: 10.0.100-rc.1.25451.107

jobs:
  build:
    runs-on: macos-26

    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0

    - name: Select Xcode ${{ env.xcodeVersion }}
      run: sudo xcode-select -s /Applications/Xcode_${{ env.xcodeVersion }}.app

    - name: Setup .NET ${{ env.dotnetVersion }}
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: ${{ env.dotnetVersion }}

    - name: Install iOS workload
      run: dotnet workload install maui ios maccatalyst
      env:
        dotnetVersion: ${{ env.dotnetVersion }}
      
    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Run the Cake script
      run: dotnet run --project build/Build.csproj --artifactsDir ${{ github.workspace }}/artifacts

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: NugetPackage
        path: ${{ github.workspace }}/artifacts
